#spring.datasource.username=root
#spring.datasource.password=root1234
#spring.jpa.hibernate.ddl-auto=update

logging:
  level:
    org:
      hibernate: error
      springframework:
        web: error
    pro:
      foreway: DEBUG

client:
  id: 9876543210
  key: 1234567890123456